# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Bartie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Go Bart
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'UIColor_Hex_Swift', '~> 4.0.2'
  pod 'Cache'
  pod 'SwiftIcons', '~> 2.2.0'
  pod 'PinLayout'

  target 'BartieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BartieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
